# Generated by Django 4.2 on 2023-04-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding',
            name='argomento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='coding',
            name='snippet',
            field=models.TextField(default=''),
        ),
    ]
