# Generated by Django 4.2 on 2023-04-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_coding_argomento_coding_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding',
            name='slug',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
