# Generated by Django 4.2 on 2023-04-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0004_alter_coding_linguaggio'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding',
            name='slug_argomento',
            field=models.SlugField(blank=True, max_length=20),
        ),
    ]
