# Generated by Django 4.2 on 2023-04-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('code_guide', models.CharField(blank=True, max_length=50)),
                ('code_img', models.ImageField(upload_to=None)),
                ('code_description', models.TextField(blank=True)),
            ],
        ),
    ]
