# Generated by Django 4.2 on 2023-04-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Homes'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='code_img',
            field=models.ImageField(blank=True, upload_to='static/img/code_img'),
        ),
    ]
