# Generated by Django 4.2 on 2023-04-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_homepage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='slug',
            field=models.SlugField(),
        ),
    ]
