# Generated by Django 4.2 on 2023-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_homepage_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tipo',
            field=models.CharField(blank=True, choices=[('LN', 'linguaggio'), ('UT', 'utilità')], max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
